Implement `InputDatasets` for BigQueryDatasetOp (#1614)
* Implement `InputDatasets` for BigQueryDatasetOp

Fixes the following warnings:

```
E tensorflow/core/framework/dataset.cc:580] UNIMPLEMENTED: Cannot compute input sources for dataset of type IO>BigQueryDataset, because the dataset does not implement `InputDatasets`.
E tensorflow/core/framework/dataset.cc:584] UNIMPLEMENTED: Cannot merge options for dataset of type IO>BigQueryDataset, because the dataset does not implement `InputDatasets`.
```

* Fix lint errors

* Replace the source for the dcmtk package

The original source for the dcmtk package is dicom.offis.de, though this
website is down, and less reliable than fetching it from github
directly. I suggest that we change this source for the github archive.